before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.builtBy=goreleaser

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - name: greentext
    homepage: https://github.com/jasonuc/greentext
    license: MIT
    folder: Formula
    description: Greentext is a 4chan greentext generator.
    tap:
      owner: jasonuc
      name: homebrew-tap
      branch: master
    commit_author:
      name: jasonuc
      email: me@jasonuc.com

release:
  prerelease: auto
  github:
    owner: jasonuc
    name: greentext
  footer: |
    ## How to Update
    ### Homebrew
    ```
      brew upgrade greentext
    ```

    ### Go
    ```
      go install github.com/jasonuc/greentext@{{ .Version }}
    ```

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Preformance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - typos
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
